# Generated by Django 6.0.4 on 2026-05-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_customer_status_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
