# Generated by Django 6.0.4 on 2026-05-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Booking Request', 'verbose_name_plural': 'Booking Requests'},
        ),
    ]
