# Generated by Django 6.0.4 on 2026-05-22 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_options'),
        ('rooms', '0005_alter_roomtype_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
