# Generated by Django 6.0.4 on 2026-05-23 08:27

from django.conf import settings
from django.db import migrations, models


def remove_duplicate_housekeeping(apps, schema_editor):
    Housekeeping = apps.get_model('housekeeping', 'Housekeeping')
    seen = set()
    for row in Housekeeping.objects.order_by('housekeeping_id'):
        key = (row.room_id, row.cleaning_date)
        if key in seen:
            row.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0001_initial'),
        ('rooms', '0005_alter_roomtype_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_housekeeping, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='housekeeping',
            constraint=models.UniqueConstraint(fields=('room', 'cleaning_date'), name='unique_housekeeping_room_per_date'),
        ),
    ]
