# Generated by Django 6.0.4 on 2026-05-27 16:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(db_column='room_id', primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=20, unique=True)),
                ('floor_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('reserved', 'Reserved'), ('cleaning', 'Cleaning In Progress')], default='available', max_length=20)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'rooms',
                'ordering': ['floor_number', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('room_type_id', models.AutoField(db_column='room_type_id', primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('max_capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Room Type',
                'verbose_name_plural': 'Room Types',
                'db_table': 'room_types',
                'ordering': ['price_per_night'],
            },
        ),
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('assignment_id', models.AutoField(db_column='assignment_id', primary_key=True, serialize=False)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to='reservations.reservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Room Assignment',
                'verbose_name_plural': 'Room Assignments',
                'db_table': 'room_assignments',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='rooms.roomtype'),
        ),
    ]
