# Generated by Django 6.0.4 on 2026-04-09 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
