# Generated by Django 6.0.4 on 2026-05-23 08:27

from django.conf import settings
from django.db import migrations, models


def remove_duplicate_reviews(apps, schema_editor):
    Review = apps.get_model('reviews', 'Review')
    seen = set()
    for row in Review.objects.order_by('review_id'):
        key = (row.customer_id, row.room_id)
        if key in seen:
            row.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('rooms', '0005_alter_roomtype_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_reviews, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('customer', 'room'), name='unique_review_per_customer_room'),
        ),
    ]
