# Generated by Django 6.0.4 on 2026-05-23 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_dedupe_and_unique_service_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='request_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='services.service'),
        ),
        migrations.AddConstraint(
            model_name='servicerequest',
            constraint=models.UniqueConstraint(fields=('request_date', 'quantity', 'status'), name='unique_service_request_per_date_qty_status'),
        ),
    ]
