# Generated by Django 6.0.4 on 2026-05-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_request_request_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='servicerequest',
            name='unique_service_request_per_date_qty_status',
        ),
        migrations.AddConstraint(
            model_name='servicerequest',
            constraint=models.UniqueConstraint(fields=('service', 'request_date', 'quantity', 'status'), name='unique_service_request_per_service_date_qty_status'),
        ),
    ]
