# Generated by Django 6.0.4 on 2026-05-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Reservation Billing Booking', 'verbose_name_plural': 'Reservation Billing Bookings'},
        ),
    ]
