# Generated by Django 6.0.5 on 2026-05-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_roomtype_rename_created_at_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='adults',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='kids',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seniors',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
