# Generated by Django 6.0.5 on 2026-05-27 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_reservation_adults_reservation_kids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='adults',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='kids',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='seniors',
        ),
    ]
