# Generated by Django 6.0.4 on 2026-04-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='Report Date')),
                ('total_bookings', models.PositiveIntegerField(default=0, verbose_name='Total Bookings')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Revenue')),
                ('occupancy_rate', models.DecimalField(decimal_places=2, default=0, help_text='Enter occupancy percentage as a number, for example 75.00', max_digits=5, verbose_name='Occupancy Rate (%)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Booking Report',
                'verbose_name_plural': 'Booking Reports',
                'ordering': ['-report_date'],
            },
        ),
    ]
