# Generated by Django 6.0.4 on 2026-05-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='occupancy_rate',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Automatically calculated from room occupancy', max_digits=5, verbose_name='Occupancy Rate (%)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Total Revenue'),
        ),
        migrations.AlterField(
            model_name='report',
            name='total_bookings',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Total Bookings'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('report_date',), name='unique_report_date'),
        ),
    ]
