# Generated by Django 6.0.4 on 2026-05-23 08:27

from django.conf import settings
from django.db import migrations, models


def remove_duplicate_staff_assignments(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            DELETE newer FROM staff_staffassignment newer
            INNER JOIN staff_staffassignment older
                ON newer.staff_id = older.staff_id
                AND newer.assigned_date = older.assigned_date
                AND newer.staff_assignment_id > older.staff_assignment_id
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_staff_assignments, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='staffassignment',
            constraint=models.UniqueConstraint(fields=('staff', 'assigned_date'), name='unique_staff_assignment_per_staff_per_date'),
        ),
    ]
