# Generated by Django 6.0.4 on 2026-05-23 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_prevent_duplicate_entries'),
        ('staff', '0002_prevent_duplicate_entries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffassignment',
            name='order',
        ),
        migrations.AddField(
            model_name='staffassignment',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffassignment',
            name='maintenance_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='maintenance.maintenancerequest'),
        ),
        migrations.AlterField(
            model_name='staffassignment',
            name='assigned_date',
            field=models.DateField(),
        ),
    ]
