# Generated by Django 6.0.4 on 2026-05-23 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staffassignment_completion_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffassignment',
            name='assigned_date',
        ),
        migrations.RemoveField(
            model_name='staffassignment',
            name='completion_date',
        ),
    ]
