# Generated by Django 6.0.4 on 2026-05-23 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_remove_staffassignment_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffassignment',
            name='order',
        ),
    ]
