# Generated by Django 4.2.7 on 2026-04-18 05:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['floor_number', 'room_number'], 'permissions': [('can_manage_rooms', 'Can add/edit/delete rooms'), ('can_update_room_status', 'Can update room status'), ('can_view_occupancy', 'Can view occupancy reports')], 'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterModelOptions(
            name='roomassignment',
            options={'ordering': ['-assigned_date'], 'permissions': [('can_assign_rooms', 'Can assign rooms to guests'), ('can_update_assignment_status', 'Can update assignment status')], 'verbose_name': 'Room Assignment', 'verbose_name_plural': 'Room Assignments'},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'ordering': ['price_per_night'], 'permissions': [('can_manage_room_types', 'Can manage room types'), ('can_view_pricing', 'Can view pricing information')], 'verbose_name': 'Room Type', 'verbose_name_plural': 'Room Types'},
        ),
        migrations.AddField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='last_occupied',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='roomassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomassignment',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes for housekeeping'),
        ),
        migrations.AddField(
            model_name='roomassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Check-In'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled')], default='pending', help_text='Current assignment status', max_length=20),
        ),
        migrations.AddField(
            model_name='roomassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active room type status'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor_number',
            field=models.IntegerField(help_text='Floor number where room is located', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, help_text='Nightly rate for this specific room (may differ from room type)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.AutoField(db_column='room_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(help_text='Room number/identifier (e.g., 101, 202A)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(help_text='Type/category of this room', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='rooms.roomtype'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('reserved', 'Reserved'), ('cleaning', 'Cleaning In Progress')], default='available', help_text='Current occupancy status', max_length=20),
        ),
        migrations.AlterField(
            model_name='roomassignment',
            name='assignment_id',
            field=models.AutoField(db_column='assignment_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roomassignment',
            name='check_in_time',
            field=models.TimeField(blank=True, help_text='Actual check-in time', null=True),
        ),
        migrations.AlterField(
            model_name='roomassignment',
            name='check_out_time',
            field=models.TimeField(blank=True, help_text='Actual check-out time', null=True),
        ),
        migrations.AlterField(
            model_name='roomassignment',
            name='room',
            field=models.ForeignKey(help_text='Room being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='capacity',
            field=models.IntegerField(help_text='Maximum number of guests this room can accommodate', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of room amenities and features'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, help_text='Base price per night (in USD)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='room_type_id',
            field=models.AutoField(db_column='room_type_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='type_name',
            field=models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('suite', 'Suite'), ('deluxe', 'Deluxe'), ('penthouse', 'Penthouse')], help_text='Unique identifier for room type', max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_number'], name='rooms_room_nu_5c8eca_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['floor_number'], name='rooms_floor_n_bc76e7_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['status'], name='rooms_status_ee4627_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_type', 'status'], name='rooms_room_ty_a7f7ec_idx'),
        ),
        migrations.AddIndex(
            model_name='roomassignment',
            index=models.Index(fields=['room', 'assigned_date'], name='room_assign_room_id_78220b_idx'),
        ),
        migrations.AddIndex(
            model_name='roomassignment',
            index=models.Index(fields=['status'], name='room_assign_status_7172ea_idx'),
        ),
        migrations.AddIndex(
            model_name='roomtype',
            index=models.Index(fields=['type_name'], name='room_types_type_na_771883_idx'),
        ),
        migrations.AddIndex(
            model_name='roomtype',
            index=models.Index(fields=['price_per_night'], name='room_types_price_p_284bc0_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(('floor_number__gte', 1)), name='valid_floor_number'),
        ),
        migrations.AlterModelTable(
            name='room',
            table='rooms',
        ),
        migrations.AlterModelTable(
            name='roomassignment',
            table='room_assignments',
        ),
        migrations.AlterModelTable(
            name='roomtype',
            table='room_types',
        ),
    ]
