# Generated by Django 4.2.7 on 2026-04-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_options_alter_roomassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='type_name',
            field=models.CharField(choices=[('standard', 'Standard Room'), ('single', 'Single Room'), ('double', 'Double Room'), ('suite', 'Suite'), ('deluxe', 'Deluxe'), ('penthouse', 'Penthouse')], help_text='Unique identifier for room type', max_length=100, unique=True),
        ),
    ]
