# Generated by Django 4.2.7 on 2026-04-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_roomtype_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='type_name',
            field=models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('suite', 'Suite'), ('deluxe', 'Deluxe'), ('penthouse', 'Penthouse')], help_text='Unique identifier for room type', max_length=100, unique=True),
        ),
    ]
