# Generated by Django 4.2.7 on 2026-04-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_roomtype_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='type_name',
            field=models.CharField(help_text='Unique identifier for room type (e.g., Single, Double, Suite, Deluxe, Penthouse, Presidential, etc.)', max_length=100, unique=True),
        ),
    ]
