# Generated by Django 6.0.4 on 2026-04-09 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price_per_night',
        ),
    ]
