# Generated by Django 6.0.4 on 2026-05-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
