# Generated by Django 6.0.4 on 2026-05-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Housekeeping',
            fields=[
                ('housekeeping_id', models.AutoField(primary_key=True, serialize=False)),
                ('cleaning_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Housekeeping',
                'verbose_name_plural': 'Housekeeping Tasks',
            },
        ),
    ]
