# Generated by Django 6.0.4 on 2026-05-16 08:36

from django.db import migrations, models


def empty_id_numbers_to_null(apps, schema_editor):
    CustomerProfile = apps.get_model('accounts', 'CustomerProfile')
    CustomerProfile.objects.filter(id_number='').update(id_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.RunPython(empty_id_numbers_to_null, migrations.RunPython.noop),
    ]
