# Generated by Django 6.0.4 on 2026-05-23 08:27

from django.conf import settings
from django.db import migrations, models


def remove_duplicate_maintenance(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            DELETE newer FROM maintenance_maintenancerequest newer
            INNER JOIN maintenance_maintenancerequest older
                ON newer.room_id = older.room_id
                AND newer.report_date = older.report_date
                AND newer.maintenance_id > older.maintenance_id
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('rooms', '0005_alter_roomtype_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_maintenance, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='maintenancerequest',
            constraint=models.UniqueConstraint(fields=('room', 'report_date'), name='unique_maintenance_room_per_report_date'),
        ),
    ]
