# Generated by Django 6.0.4 on 2026-05-23 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0002_alter_housekeeping_staff'),
        ('maintenance', '0002_alter_maintenancerequest_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='priority',
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='housekeeping',
            field=models.ForeignKey(blank=True, help_text='Optional link: one housekeeping task may have many maintenance requests.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='housekeeping.housekeeping'),
        ),
    ]
