# Generated by Django 6.0.4 on 2026-04-09 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id_type',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
    ]
